name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        PASSWD: ${{ secrets.PASSWD }}
        ALIAS: ${{ secrets.ALIAS }}
      run: |
        echo "storePassword=$PASSWD" >> keystore.properties
        echo "keyPassword=$PASSWD" >> keystore.properties
        echo "keyAlias=$ALIAS" >> keystore.properties
        echo "storeFile=keystore.jks" >> keystore.properties
        ./gradlew assembleRelease
